import Head from 'next/head'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import ErrorDisplay from '../components/ErrorDisplay'
import styles from '../styles/Home.module.css'
import AuthForm from '../components/auth/AuthForm'
import BlogList from '../components/blog/BlogList'

export default function Home() {
  const [isLoggedIn, setIsLoggedIn] = useState(false)
  const [user, setUser] = useState({})
  const [token, setToken] = useState('')
  const [error, setError] = useState('')
  const [posts, setPosts] = useState([])

  useEffect(() => {
    const storedData = JSON.parse(localStorage.getItem('userdata'))
    if (storedData) {
      const {token, user} = storedData
    if (storedData.token) {
      setToken(token)
      setUser(user)
      setIsLoggedIn(true)
    }
    }
  }, [])

  useEffect(() => {
    if (!isLoggedIn) {
     setPosts([]) 
    } else {
      const fetchPosts = async () => {
        const fetchedPosts = await fetch('http://localhost:5000/api/posts', {
          method: 'GET',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
          }
        })
        const fetchedPostsJSON = await fetchedPosts.json()
        return fetchedPostsJSON
      }
      fetchPosts().then(data => {
        setPosts(data.posts)
      })
    }
  }, [isLoggedIn, token, setPosts])

  const logoutHandler = () => {
    setIsLoggedIn(false)
  }

  if (error) {
    return <ErrorDisplay error={error} setError={setError} />
  }

  if (!isLoggedIn) {
    return <AuthForm setIsLoggedIn={setIsLoggedIn} setToken={setToken} setUser={setUser} setError={setError} />
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href='/profile'>
          <a>Check your profile</a>
        </Link>
        <Link href='/blog/post'>
          <a>Add a post</a>
        </Link>
        <p>yeeeeet</p><br />
        <button onClick={logoutHandler}>Logout</button><br />
        <BlogList posts={posts} />
      </main>

    </div>
  )
}
